// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCapture(arg1) {
  return window['go']['main']['App']['DeleteCapture'](arg1);
}

export function GetAudioLevels() {
  return window['go']['main']['App']['GetAudioLevels']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function ListCaptures() {
  return window['go']['main']['App']['ListCaptures']();
}

export function StartHeadlessServer() {
  return window['go']['main']['App']['StartHeadlessServer']();
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
