// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCapture(arg1:string):Promise<boolean>;

export function GetAudioLevels():Promise<Array<number>>;

export function GetOS():Promise<string>;

export function GetSystemStats():Promise<main.SystemStats>;

export function ListCaptures():Promise<Array<main.FileInfo>>;

export function ToggleRecording():Promise<boolean>;

export function UpdateConfig(arg1:main.CameraSettings):Promise<void>;
